import React, { useEffect, useState } from "react";
import MUIDataTable from "mui-datatables";
import { Box } from "@mui/material";

function SuperInvestor() {
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch("api/superinvestor")
      .then((response) => response.json())
      .then((data) => {
        setData(data);
        console.log(data.data);
      });
  }, []);

  const columns = [
    {
      name: "ID",
      options: {
        display: false,
      },
    },
    {
      name: "CIK",
      options: {
        display: false,
      },
    },
    "Name",
    "Company",
    "Notes",
    "Ticket",
    "flag",
    {
      name: "Category ID",
      options: {
        display: false,
      },
    },

    {
      name: "Insert Date",
      options: {
        display: false,
      },
    },
    {
      name: "Update Date",
      options: {
        display: false,
      },
    },
    {
      name: "Insert By",
      options: {
        display: false,
      },
    },
    {
      name: "Update By",
      options: {
        display: false,
      },
    },
    "Cutoff Date",
    "Latest Checked Date",
  ];
  const options = {
    filterType: "checkbox",
  };
  return (
    <Box sx={{ mx: "20px" }}>
      <MUIDataTable
        title={"Super Investors List"}
        data={
          typeof data.data === "undefined"
            ? console.log("LOADING...")
            : data.data.map(function (object, i) {
                return [
                  object.id,
                  object.si_cik,
                  object.si_name,
                  object.si_company,
                  object.si_notes,
                  object.ticker,
                  object.flag,
                  object.category_id,
                  object.insert_date,
                  object.update_date,
                  object.insert_by,
                  object.update_by,
                  object.cutoff_date,
                  object.latest_checked_date,
                ];
              })
        }
        // {data1.data.map((data, i) => {

        // })}
        columns={columns}
        options={options}
      />
    </Box>
  );
}

const data1 = {
  data: [
    {
      id: 131,
      si_cik: 1106500,
      si_name: "Robert Karr",
      si_company: "Joho Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 132,
      si_cik: 1128452,
      si_name: "Wilbur Ross",
      si_company: "WL Ross",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 133,
      si_cik: 1134406,
      si_name: "James Crichton",
      si_company: "Scout Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 134,
      si_cik: 1136704,
      si_name: "Financials: Tom Brown",
      si_company: "Second Curve Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 135,
      si_cik: 1138995,
      si_name: "Larry Robbins",
      si_company: "Glenview Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 136,
      si_cik: 1167483,
      si_name: "Technology: Charles Coleman",
      si_company: "Tiger Global",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 137,
      si_cik: 1168664,
      si_name: "Alan Fournier",
      si_company: "Pennant Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 138,
      si_cik: 1173334,
      si_name: "Mohnish Pabrai",
      si_company: "Pabrai Investment Funds",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 139,
      si_cik: 1218269,
      si_name: "Energy: Boone Pickens",
      si_company: "BP Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 140,
      si_cik: 1220338,
      si_name: "Stephen Clearman and Tushar Shah",
      si_company: "Kinderhook Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 141,
      si_cik: 1276537,
      si_name: "Paul Orfalea and Lance Helfert",
      si_company: "West Coast Asset Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 142,
      si_cik: 1277742,
      si_name: "Mark Rachesky",
      si_company: "MHR Fund Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 143,
      si_cik: 1278951,
      si_name: "Steve Tananbaum",
      si_company: "GoldenTree Asset Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 144,
      si_cik: 1316729,
      si_name: "John Lewis",
      si_company: "Osmium Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 145,
      si_cik: 1306923,
      si_name: "Pharma: Will Edwards",
      si_company: "Palo Alto Investors",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 146,
      si_cik: 1312908,
      si_name: "Jeffrey Gates",
      si_company: "Gates Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 147,
      si_cik: 1317601,
      si_name: "Robert Jaffe",
      si_company: "Force Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 148,
      si_cik: 1325256,
      si_name: "Clifton Robbins",
      si_company: "Blue Harbour Group",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 149,
      si_cik: 1336528,
      si_name: "Bill Ackman",
      si_company: "Pershing Square Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 150,
      si_cik: 1340807,
      si_name: "Brian Bares",
      si_company: "Bares Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 151,
      si_cik: 1353316,
      si_name: "Jonathan Auerbach",
      si_company: "Hound Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 152,
      si_cik: 1360079,
      si_name: "David Winters",
      si_company: "Wintergreen Advisers",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 153,
      si_cik: 1362598,
      si_name: "Chris Hohn",
      si_company: "The Childrens Investment Fund",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 154,
      si_cik: 1364412,
      si_name: "Rehan Jaffer and Usman Nabi",
      si_company: "H Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 155,
      si_cik: 1376259,
      si_name: "Richard Breeden",
      si_company: "Breeden Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 156,
      si_cik: 1389563,
      si_name: "Ed Gilhuly and Scott Stuart",
      si_company: "Sageview Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 157,
      si_cik: 1410352,
      si_name: "Lisa Rapuano",
      si_company: "Lane Five Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 158,
      si_cik: 1412093,
      si_name: "Carl Icahn",
      si_company: "Icahn Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 159,
      si_cik: 1453039,
      si_name: "Zeke Ashton",
      si_company: "Centaur Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 160,
      si_cik: 1469209,
      si_name: "Meryl Witmer",
      si_company: "Eagle Value Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 161,
      si_cik: 1541996,
      si_name: "Mick McGuire",
      si_company: "Marcato Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 162,
      si_cik: 1568820,
      si_name: "Allan Mecham",
      si_company: "Arlington Value Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 163,
      si_cik: 789920,
      si_name: "Glenn Greenberg",
      si_company: "Brave Warrior Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 164,
      si_cik: 859804,
      si_name: "Tony Guerrerio and David Rolfe",
      si_company: "Wedgewood Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 165,
      si_cik: 860585,
      si_name: "Eddie Lampert",
      si_company: "ESL Investments",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 166,
      si_cik: 883965,
      si_name: "Wally Weitz",
      si_company: "Wallace R. Weitz & Company",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 167,
      si_cik: 945631,
      si_name: "Boykin Curry",
      si_company: "Eagle Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 168,
      si_cik: 1169581,
      si_name: "Paul OLeary",
      si_company: "Raffles Associates",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 169,
      si_cik: 1418814,
      si_name: "Jeffrey Ubben",
      si_company: "ValueAct Holdings",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 170,
      si_cik: 1027796,
      si_name: "Rich Pzena",
      si_company: "Pzena Investment Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 171,
      si_cik: 846222,
      si_name: "Ed Wachenheim",
      si_company: "Greenhaven Associates",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 172,
      si_cik: 1105838,
      si_name: "Robert Robotti",
      si_company: "Robotti & Company",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 173,
      si_cik: 1389403,
      si_name: "Francis Chou",
      si_company: "Chou Associates Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 174,
      si_cik: 1483866,
      si_name: "Hassan Elmasry",
      si_company: "Independent Franchise Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 175,
      si_cik: 1096343,
      si_name: "Tom Gayner",
      si_company: "Markel Corporation",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 176,
      si_cik: 1273087,
      si_name: "Israel Englander",
      si_company: "Millennium Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 177,
      si_cik: 1035674,
      si_name: "John Paulson",
      si_company: "Paulson & Co.",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 178,
      si_cik: 96223,
      si_name: "Ian Cumming and Joe Steinberg",
      si_company: "Leucadia National",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 179,
      si_cik: 807985,
      si_name: "Mason Hawkins",
      si_company: "Southeastern Asset Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 180,
      si_cik: 1040273,
      si_name: "Dan Loeb",
      si_company: "Third Point",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 181,
      si_cik: 1456417,
      si_name: "Charles de Vaulx",
      si_company: "International Value Advisers",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 182,
      si_cik: 915191,
      si_name: "Prem Watsa",
      si_company: "Fairfax Financial Holdings",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 183,
      si_cik: 1006438,
      si_name: "David Tepper",
      si_company: "Appaloosa Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 184,
      si_cik: 1056258,
      si_name: "John Griffin",
      si_company: "Blue Ridge Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 185,
      si_cik: 1061768,
      si_name: "Seth Klarman",
      si_company: "Baupost Group",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 186,
      si_cik: 1063296,
      si_name: "Alexander Roepers",
      si_company: "Atlantic Investment Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 187,
      si_cik: 1067983,
      si_name: "Warren Buffett",
      si_company: "Berkshire Hathaway",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 188,
      si_cik: 1079114,
      si_name: "David Einhorn",
      si_company: "Greenlight Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 189,
      si_cik: 1105497,
      si_name: "Glenn Fuhrman and John Phelan",
      si_company: "MSD Capital",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 190,
      si_cik: 1056831,
      si_name: "Bruce Berkowitz",
      si_company: "Fairholme Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 191,
      si_cik: 1484836,
      si_name: "Mark Gallogly and Jeffrey Aronson",
      si_company: "Centerbridge Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 192,
      si_cik: 949119,
      si_name: "Lloyd Miller III",
      si_company: "micro-cap equities",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 193,
      si_cik: 1112520,
      si_name: "Chuck Akre",
      si_company: "Akre Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 194,
      si_cik: 1478982,
      si_name: "Toby Symonds",
      si_company: "Altai Capital Management",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
    {
      id: 195,
      si_cik: 1313926,
      si_name: "Sandy Nairn",
      si_company: "Edinburgh Partners",
      si_notes: "nan",
      ticker: "nan",
      flag: "Y",
      category_id: -1,
      insert_date: "nan",
      update_date: "nan",
      insert_by: "nan",
      update_by: "nan",
      cutoff_date: "2022-11-25",
      latest_checked_date: "2022-12-05",
    },
  ],
};

export default SuperInvestor;
